root: ./

redirects:
  help: getting-started/quick-start-with-akto-cloud.md
  api-inventory: api-inventory/concepts/api-endpoints.md
  api-inventory/api-inventory: api-inventory/concepts/api-endpoints.md
  api-inventory/api-collections: api-inventory/concepts/api-collection.md
  api-inventory/handeling-shadow-apis: api-inventory/concepts/meta-properties-of-api-endpoint.md
  api-inventory/unauthenticated-apis: api-inventory/concepts/meta-properties-of-api-endpoint.md
  api-inventory/detecting-changes-in-apis: api-inventory/concepts/api-changes.md
  api-inventory/detecting-changes-in-apis/webhook-alerts: api-inventory/concepts/alerts.md
  api-inventory/auth-types: api-inventory/concepts/auth-types.md
  api-inventory/sensitive-data: api-inventory/concepts/sensitive-data.md
  api-inventory/api-documentation: api-inventory/how-to/create-swagger-file-using-akto.md
  api-inventory/data-types: api-inventory/concepts/data-type.md
  test-editor/overview: test-editor/concepts/overview.md
  test-editor/test-library: test-editor/concepts/test-library.md
  test-editor/test-library/local-file-inclusion-with-akto: test-editor/concepts/template-yamls/local-file-inclusion-with-akto.md
  test-editor/concepts/test-library/local-file-inclusion-with-akto: test-editor/concepts/template-yamls/local-file-inclusion-with-akto.md
  test-editor/test-yaml-syntax-one-pager: test-editor/concepts/test-yaml.md
  test-editor/test-yaml-syntax-detailed: test-editor/concepts/test-yaml-syntax-detailed.md
  test-editor/test-yaml-syntax-detailed/id: test-editor/concepts/test-yaml-syntax-detailed/id.md
  test-editor/test-yaml-syntax-detailed/info: test-editor/concepts/test-yaml-syntax-detailed/info.md
  test-editor/test-yaml-syntax-detailed/api-selection-filters: test-editor/concepts/test-yaml-syntax-detailed/api-selection-filters.md
  test-editor/test-yaml-syntax-detailed/execute: test-editor/concepts/test-yaml-syntax-detailed/execute.md
  test-editor/test-yaml-syntax-detailed/auth: test-editor/concepts/test-yaml-syntax-detailed/auth.md
  test-editor/test-yaml-syntax-detailed/validation: test-editor/concepts/test-yaml-syntax-detailed/validation.md
  test-editor/editing-built-in-test: test-editor/how-to/edit-test.md
  test-editor/writing-custom-tests: test-editor/how-to/create-a-custom-test.md
  testing/run-tests-in-cicd: api-security-testing/how-to/run-tests-in-cicd.md
  testing/github_integration_testing: api-security-testing/how-to/setup-github-integration-for-ci-cd.md
  testing/github_integration_testing/github_app_integration: api-security-testing/how-to/setup-github-integration-for-ci-cd/create-github-app.md
  testing/run-test: api-security-testing/how-to/run-test.md
  testing/create-user-config: api-security-testing/concepts/user-config.md
  testing/run-tests-in-cli-using-akto: api-security-testing/how-to/run-tests-in-cli-using-akto.md
  testing/test-results: api-security-testing/concepts/test-result.md
  testing/test-library: test-editor/concepts/test-library.md
  testing/user-roles: api-security-testing/concepts/test-role.md
  testing/run-test-in-graphql: api-security-testing/how-to/secure-graphql-apis-using-akto.md
  add-api-data/integrations: traffic-connections/traffic-data-sources.md
  getting-started/aws-deploy: getting-started/quick-start-with-akto-self-hosted/aws-deploy.md
  getting-started/aws-multi-vpc-deploy: getting-started/quick-start-with-akto-self-hosted/aws-deploy/aws-multi-vpc-deploy.md
  getting-started/aws-cross-region-vpc-deploy: getting-started/quick-start-with-akto-self-hosted/aws-deploy/aws-cross-region-vpc-deploy.md
  getting-started/helm-deploy: getting-started/quick-start-with-akto-self-hosted/helm-deploy.md
  getting-started/heroku: getting-started/quick-start-with-akto-self-hosted/heroku.md
  getting-started/openshift-deploy: getting-started/quick-start-with-akto-self-hosted/openshift-deploy.md
  getting-started/gcp-deploy: getting-started/quick-start-with-akto-self-hosted/gcp-deploy.md
  getting-started/azure-deploy: getting-started/quick-start-with-akto-self-hosted/azure-deploy.md
  getting-started/aws-ssl: getting-started/quick-start-with-akto-self-hosted/aws-ssl.md
  sso/azuread-saml: account/sso/azuread-saml.md
  sso/okta-oidc: account/sso/okta-oidc.md
  sso/github-oidc: account/sso/github-oidc.md
  traffic-connections/traffic-data-sources/hybrid-saas: getting-started/traffic-processor/hybrid-saas.md
  traffic-connections/traffic-data-sources/amazon-aws: traffic-connector/mirroring/amazon-aws.md
  traffic-connections/traffic-data-sources/aws-eks: traffic-connector/aws-services/aws-eks.md
  traffic-connections/traffic-data-sources/aws-fargate: traffic-connector/aws-services/aws-fargate.md
  traffic-connections/traffic-data-sources/aws-ecs: traffic-connector/aws-services/aws-ecs.md
  traffic-connections/traffic-data-sources/aws-beanstalk: traffic-connector/aws-services/aws-beanstalk.md
  traffic-connections/traffic-data-sources/kubernetes: traffic-connector/kubernetes/kubernetes.md
  traffic-connections/traffic-data-sources/aws-api-gateway: traffic-connector/aws-services/aws-api-gateway.md
  traffic-connections/traffic-data-sources/kong: traffic-connector/api-gateways/kong.md
  traffic-connections/traffic-data-sources/nginx: traffic-connector/api-gateways/nginx.md
  traffic-connections/traffic-data-sources/envoy: traffic-connector/api-gateways/envoy.md
  traffic-connections/traffic-data-sources/envoy-1: traffic-connector/api-gateways/envoy-1.md
  traffic-connections/traffic-data-sources/docker: traffic-connector/virtual-machines/docker.md
  traffic-connections/traffic-data-sources/tcp-agent: traffic-connector/virtual-machines/tcp-agent.md
  traffic-connections/traffic-data-sources/ebpf: traffic-connector/ebpf/ebpf.md
  traffic-connections/traffic-data-sources/ebpf-mtls: traffic-connector/ebpf/ebpf-mtls.md
  traffic-connections/traffic-data-sources/data-processor: getting-started/traffic-processor.md
  traffic-connections/traffic-data-sources/har-file-upload: traffic-connector/manual/har-file-upload.md
  traffic-connections/traffic-data-sources/google-cloud-gcp: traffic-connector/mirroring/google-cloud-gcp.md
  traffic-connections/traffic-data-sources/burp-suite: traffic-connector/manual/burp-suite.md
  traffic-connections/traffic-data-sources/postman: traffic-connector/manual/postman.md
  traffic-connections/traffic-data-sources/openapi: traffic-connector/manual/openapi.md
  traffic-connections/traffic-data-sources/akto-sdk: traffic-connector/akto-sdk.md
  getting-started/quick-start-with-akto-self-hosted/helm-deploy: getting-started/traffic-processor/helm-deploy.md
  getting-started/quick-start-with-akto-self-hosted/gcp-deploy: getting-started/traffic-processor/gcp-deploy.md
  getting-started/quick-start-with-akto-self-hosted/azure-deploy: getting-started/traffic-processor/azure-deploy.md
  getting-started/quick-start-with-akto-self-hosted/openshift-deploy: getting-started/traffic-processor/openshift-deploy.md
  getting-started/quick-start-with-akto-self-hosted/heroku: getting-started/traffic-processor/heroku.md
  getting-started/quick-start-with-akto-self-hosted/aws-ssl: getting-started/akto-self-hosted/aws-ssl.md
  getting-started/proxy-setup: getting-started/advanced-topics/proxy-setup.md
  getting-started/move-self-hosted-to-saas: getting-started/advanced-topics/move-self-hosted-to-saas.md

