root: ./

redirects:
  help: getting-started/quick-start-with-akto-cloud.md
  api-inventory: api-inventory/concepts/api-endpoints.md
  api-inventory/api-inventory: api-inventory/concepts/api-endpoints.md
  api-inventory/api-collections: api-inventory/concepts/api-collection.md
  api-inventory/handeling-shadow-apis: api-inventory/concepts/meta-properties-of-api-endpoint.md
  api-inventory/unauthenticated-apis: api-inventory/concepts/meta-properties-of-api-endpoint.md
  api-inventory/detecting-changes-in-apis: api-inventory/concepts/api-changes.md
  api-inventory/detecting-changes-in-apis/webhook-alerts: api-inventory/concepts/alerts.md
  api-inventory/auth-types: api-inventory/concepts/auth-types.md
  api-inventory/sensitive-data: api-inventory/concepts/sensitive-data.md
  api-inventory/api-documentation: api-inventory/how-to/create-swagger-file-using-akto.md
  api-inventory/data-types: api-inventory/concepts/data-type.md
  test-editor/overview: test-editor/concepts/overview.md
  test-editor/test-library: test-editor/concepts/test-library.md
  test-editor/test-library/local-file-inclusion-with-akto: test-editor/concepts/test-library/local-file-inclusion-with-akto.md
  test-editor/test-yaml-syntax-one-pager: test-editor/concepts/test-yaml.md
  test-editor/test-yaml-syntax-detailed: test-editor/concepts/test-yaml-syntax-detailed.md
  test-editor/test-yaml-syntax-detailed/id: test-editor/concepts/test-yaml-syntax-detailed/id.md
  test-editor/test-yaml-syntax-detailed/info: test-editor/concepts/test-yaml-syntax-detailed/info.md
  test-editor/test-yaml-syntax-detailed/api-selection-filters: test-editor/concepts/test-yaml-syntax-detailed/api-selection-filters.md
  test-editor/test-yaml-syntax-detailed/execute: test-editor/concepts/test-yaml-syntax-detailed/execute.md
  test-editor/test-yaml-syntax-detailed/auth: test-editor/concepts/test-yaml-syntax-detailed/auth.md
  test-editor/test-yaml-syntax-detailed/validation: test-editor/concepts/test-yaml-syntax-detailed/validation.md
  test-editor/editing-built-in-test: test-editor/how-to/edit-test.md
  test-editor/writing-custom-tests: test-editor/how-to/create-a-custom-test.md
  testing/run-tests-in-cicd: api-security-testing/how-to/run-tests-in-cicd.md
  testing/github_integration_testing: api-security-testing/how-to/setup-github-integration-for-ci-cd.md
  testing/github_integration_testing/github_app_integration: api-security-testing/how-to/setup-github-integration-for-ci-cd/create-github-app.md
  testing/run-test: api-security-testing/how-to/run-test.md
  testing/create-user-config: api-security-testing/concepts/user-config.md
  testing/run-tests-in-cli-using-akto: api-security-testing/how-to/run-tests-in-cli-using-akto.md
  testing/test-results: api-security-testing/concepts/test-result.md
  testing/test-library: test-editor/concepts/test-library/
  testing/user-roles: api-security-testing/concepts/test-role.md
  testing/run-test-in-graphql: api-security-testing/how-to/secure-graphql-apis-using-akto.md
  add-api-data/integrations: traffic-connections/traffic-data-sources.md
  
  
