name: Sync readme
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - action
jobs:
  Sync-Readme:
    runs-on: ubuntu-latest
    steps:
      - name: Sync readme2
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'README.md'
          destination_repo: 'akto-api-security/dummy'
          user_email: 'ankush@akto.io'
          user_name: 'Ankush Jain'
          destination_branch: 'master'
          
