name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - action3
jobs:
  Sync-Readme:
    runs-on: ubuntu-latest
    steps:
      - name: Sync readme
        uses: nkoppel/push-files-to-another-repository@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'README.md'
          destination-username: 'akto-api-security'
          destination-repository: 'dummy'
          commit-email: 'ankita@akto.io'